**HW Pandas Intro**
Using the cleaned CSV file from the previous homework, create a Jupyter Notebook that opens and explores the data using pandas.

Use the following methods:

df.head()

df.shape

df.columns

df.dtypes

df.info()

Also use a mask to create a dataframe with less rows.

In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [8]:
import csv

filename = "/Users/carolinedegroodt/Downloads/Geog 592/geog592-carodeg/homework/week04/Data/cleanedanalytic_data2025_v3.csv"

with open(filename, "r", encoding="utf-8-sig") as file:
    reader = csv.reader(file)
    rows = list(reader)

print("Number of Rows:", len(rows))

Number of Rows: 3205

definitions.
- **Class** : a template that defines the kind of data and behavior needed to create an *object*.
- **Object** :  one actual instance created from a class.  Objects in a class have *attributes* and *methods.*
- **Attribute** : refers to specific data that belongs to an object. 
- **Method** : refers to a function that belongs to the object; usually all objects of the same class have the same methods (but the methods' behaviour can depent on the specific attributes)

In [10]:
# Read a csv into a pandas dataframe
filename = "cleanedanalytic_data2025_v3.csv"
df = pd.read_csv(filename)

In [11]:
type(df)

pandas.DataFrame

The important part of the result is `DataFrame`.

So now we can apply the vocabulary from our `Point` example:

```text
pandas.DataFrame   -> class
df                 -> object
head()             -> method
shape              -> attribute

**Head**
Head is a method that performs an action using the object. 
methods use df.()

In [14]:
df.head(3)

   State FIPS Code  Premature Death Black  Premature Death White  FIPS Code
0                0           13698.397493            8038.489963          0
1                1           15767.493943           10855.355098       1000
2                1           14123.416478            9204.935423       1001

**shape**
shape is an attribute- an attribute stores or reports information about the object.
shows as (rows, columns)
attributes use df.

In [13]:
df.shape

(3204, 4)

In [15]:
df.columns

Index(['State FIPS Code', 'Premature Death Black', 'Premature Death White',
       'FIPS Code'],
      dtype='str')

In [16]:
df.dtypes

State FIPS Code            int64
Premature Death Black    float64
Premature Death White    float64
FIPS Code                  int64
dtype: object

**Info**
Info reports column names, non-null counts, and data types.

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3204 entries, 0 to 3203
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State FIPS Code        3204 non-null   int64
 1   Premature Death Black  1495 non-null   float64
 2   Premature Death White  3101 non-null   float64
 3   FIPS Code              3204 non-null   int64
dtypes: float64(2), int64(2)
memory usage: 100.3 KB

**Creating a mask**
comparing premature deaths

In [ ]:
mask = df["Premature Death Black"] > 30000

df2 = df[mask]

df2 #keeps only rows where condition is true

      State FIPS Code  Premature Death Black  Premature Death White  FIPS Code
508                13           31551.265667           19732.582587      13201
702                17           30451.696151           11687.945844      17165
717                17           31212.537933            9790.728902      17195
965                20           31325.326661            9340.917453      20099
1069               21           51329.093817           20460.640633      21095
1118               21           46653.963529           21557.736024      21193
1531               29           31308.994905           15278.692562      29023
2130               39           35369.065416           13054.474597      39081
2162               39           30363.489097           16997.178712      39145
2330               42           32042.889591           10944.236895      42073
2517               47           30669.527499           14637.310549      47071

In [24]:
mask = df["Premature Death White"] > 30000

df2 = df[mask] #keep only rows where condition is true

df2

      State FIPS Code  Premature Death Black  Premature Death White  FIPS Code
2998               51            23869.95215           31780.606227      51730